"""add_start_date_to_category_schedule

Revision ID: 3c3b20beff0a
Revises: 44af4d1fbe4f
Create Date: 2026-01-20 21:19:24.249998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3b20beff0a'
down_revision: Union[str, Sequence[str], None] = '44af4d1fbe4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_schedules', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category_schedules', 'start_date')
    # ### end Alembic commands ###
